[project]
name = "sentiment-analysis-summary"
version = "0.1.0"
dependencies = [
    "tf-keras",
    "numpy",
    "transformers",
    "torch",
    "dotenv>=0.9.9",
    "nltk>=3.9.1",
    "tensorflow-datasets>=4.9.9",
]
